sudo: false

language: node_js

node_js:
  - '0.10'
  - '0.12'
  - '4'
  - '5'
  - '6'

addons:
  apt:
    packages:
    - aria2

before_script:
  - npm install -g mocha standard
  - aria2c -v

script:
  - npm test
  - aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all --daemon
  - npm run integration
