name: Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20, 22, 24 ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        env:
          MAX_RETRIES: ${{ vars.MAX_RETRIES }}
          RETRY_DELAY: ${{ vars.RETRY_DELAY }}
        run: |
          
          - name: Test
            run: |
              while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
                echo "--- Running tests (Attempt $((RETRY_COUNT + 1))/$MAX_RETRIES) ---"
                npm run test || {
                  if [ $RETRY_COUNT -eq $(($MAX_RETRIES - 1)) ]; then
                    echo "Tests failed permanently after $MAX_RETRIES attempts."
                    exit 1
                  fi
                  echo "Test command failed. Retrying in $RETRY_DELAY seconds..."
                  sleep $RETRY_DELAY
                }
                RETRY_COUNT=$((RETRY_COUNT + 1))
              done

      - name: Build
        run: npm run build
